export type SceneKey = 'base' | 'mall' | 'office' | 'task';
export const scenes = [
  {
    key: 'base' as const,
    label: '系统管理',
    eyebrow: 'SYSTEM OVERVIEW',
    title: '让管理，更有条理。',
    description: '统一管理组织、权限与系统资源，掌握服务运行状态。',
    color: '#3665ed',
    icon: 'ele-Grid',
  },
  {
    key: 'mall' as const,
    label: '商城运营',
    eyebrow: 'COMMERCE WORKSPACE',
    title: '每一笔生意，都在掌握。',
    description: '从销售趋势到订单履约，为今天的经营找到重点。',
    color: '#138b78',
    icon: 'ele-ShoppingBag',
  },
  {
    key: 'office' as const,
    label: '协同办公',
    eyebrow: 'TEAM WORKSPACE',
    title: '把协作，变成日常。',
    description: '聚焦待办、日程与团队动态，让每一天井然有序。',
    color: '#7955d9',
    icon: 'ele-OfficeBuilding',
  },
  {
    key: 'task' as const,
    label: '项目管理',
    eyebrow: 'PROJECT WORKSPACE',
    title: '清晰目标，稳步向前。',
    description: '连接计划与执行，看见项目进度和团队的每一步。',
    color: '#d07735',
    icon: 'ele-Flag',
  },
];
export const metrics = {
  mall: [
    ['今日成交额', '¥ 28,640', '较昨日 +12.8%', 'ele-Wallet'],
    ['支付订单', '186', '较昨日 +8.2%', 'ele-ShoppingCart'],
    ['新增会员', '42', '较昨日 +6.5%', 'ele-User'],
    ['待发货', '24', '履约事项待处理', 'ele-Box'],
  ],
  office: [
    ['待我审批', '8', '其中 2 项优先处理', 'ele-DocumentChecked'],
    ['今日会议', '3', '下一场 14:00', 'ele-Calendar'],
    ['团队成员', '32', '协作团队 · 示例', 'ele-User'],
    ['本周完成', '86%', '周目标完成进度', 'ele-CircleCheck'],
  ],
  task: [
    ['进行中项目', '6', '项目组合 · 示例', 'ele-FolderOpened'],
    ['待办任务', '18', '其中 3 项高优先级', 'ele-List'],
    ['本周完成', '24', '较上周 +4 项', 'ele-CircleCheck'],
    ['按期完成率', '92%', '本月目标 95%', 'ele-Timer'],
  ],
};
export const demoOrders = [
  {
    id: 'MMS20261006001',
    name: '极简桌面收纳套装',
    customer: '陈女士',
    amount: '¥ 268.00',
    status: '待发货',
  },
  {
    id: 'MMS20261006002',
    name: '轻量通勤双肩包',
    customer: '林先生',
    amount: '¥ 399.00',
    status: '已支付',
  },
  {
    id: 'MMS20261006003',
    name: '无线便携键盘',
    customer: '张先生',
    amount: '¥ 329.00',
    status: '已完成',
  },
  {
    id: 'MMS20261006004',
    name: '陶瓷咖啡杯礼盒',
    customer: '李女士',
    amount: '¥ 158.00',
    status: '待发货',
  },
];
export const approvals = [
  {
    title: '产品团队 · 采购申请',
    person: '陈悦',
    type: '采购',
    detail: '办公设备采购 / ¥ 3,600',
    time: '10:32',
    urgent: true,
  },
  {
    title: '市场团队 · 费用报销',
    person: '林宇',
    type: '报销',
    detail: '客户拜访交通与差旅',
    time: '09:48',
    urgent: false,
  },
  {
    title: '研发团队 · 请假申请',
    person: '王宁',
    type: '请假',
    detail: '10 月 08 日 / 1 天',
    time: '09:15',
    urgent: false,
  },
  {
    title: '设计团队 · 合同审批',
    person: '苏晴',
    type: '合同',
    detail: '年度设计服务合作',
    time: '昨天',
    urgent: true,
  },
];
export const demoTasks = [
  {
    title: '统一登录体验设计',
    project: '管理后台升级',
    owner: '陈悦',
    initials: '悦',
    priority: '高',
    stage: '待开始',
    date: '10/08',
    progress: 0,
  },
  {
    title: '梳理订单状态流转',
    project: '商城迭代',
    owner: '林宇',
    initials: '宇',
    priority: '高',
    stage: '进行中',
    date: '10/09',
    progress: 65,
  },
  {
    title: '移动端布局适配',
    project: '管理后台升级',
    owner: '苏晴',
    initials: '晴',
    priority: '中',
    stage: '进行中',
    date: '10/10',
    progress: 40,
  },
  {
    title: '业务接口评审',
    project: '商城迭代',
    owner: '王宁',
    initials: '宁',
    priority: '中',
    stage: '待验收',
    date: '10/07',
    progress: 90,
  },
  {
    title: '组件规范整理',
    project: '管理后台升级',
    owner: '陈悦',
    initials: '悦',
    priority: '低',
    stage: '已完成',
    date: '10/06',
    progress: 100,
  },
  {
    title: '权限矩阵核对',
    project: '管理后台升级',
    owner: '林宇',
    initials: '宇',
    priority: '高',
    stage: '待开始',
    date: '10/11',
    progress: 0,
  },
];
