/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animate: typeof import('./src/components/animate/index.vue')['default']
    Auth: typeof import('./src/components/auth/auth.vue')['default']
    AuthAll: typeof import('./src/components/auth/authAll.vue')['default']
    Auths: typeof import('./src/components/auth/auths.vue')['default']
    Chat: typeof import('./src/components/chat-room/chat.vue')['default']
    ChatCopy: typeof import('./src/components/chat-room/chat-copy.vue')['default']
    City: typeof import('./src/components/city/index.vue')['default']
    Cropper: typeof import('./src/components/cropper/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FastEditor: typeof import('./src/components/fast-editor/src/fast-editor.vue')['default']
    FastRadioCheckbox: typeof import('./src/components/fast-radio-checkbox/src/fast-radio-checkbox.vue')['default']
    FastRadioGroup: typeof import('./src/components/fast-radio-group/src/fast-radio-group.vue')['default']
    FastSelect: typeof import('./src/components/fast-select/src/fast-select.vue')['default']
    FastSwitch: typeof import('./src/components/fast-switch/src/fast-switch.vue')['default']
    FastTableColumn: typeof import('./src/components/fast-table-column/src/fast-table-column.vue')['default']
    File: typeof import('./src/components/fast-upload/file.vue')['default']
    IconSelector: typeof import('./src/components/iconSelector/index.vue')['default']
    Img: typeof import('./src/components/fast-upload/img.vue')['default']
    ImgCropper: typeof import('./src/components/fast-upload/img-cropper.vue')['default']
    ImgPreview: typeof import('./src/components/fast-upload/img-preview.vue')['default']
    Imgs: typeof import('./src/components/fast-upload/imgs.vue')['default']
    List: typeof import('./src/components/iconSelector/list.vue')['default']
    NoticeBar: typeof import('./src/components/noticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon/src/svg-icon.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
    TableTool: typeof import('./src/components/table-tool/index.vue')['default']
    VideoPlayer: typeof import('./src/components/video-player/index.vue')['default']
  }
}
