/** 安全 re-export：纯校验函数，零 import */
export {
  verify,
  numberPercentage,
  numberPercentageFloat,
  numberIntegerAndFloat,
  numberInteger,
  textColor,
  phone,
  elPhone,
  telPhone,
  email,
  elEmail,
  idCard,
  url,
  password,
  passwordPowerful,
  passwordStrength,
  computePasswordStrengthLevel,
  iPAddress,
  fullName,
  postalCode,
  carNum,
  account,
  cnAndSpace,
  enAndSpace,
  andSpace,
  numberComma,
  numberCnUppercase,
} from '/@/utils/toolsValidate';
export type { PasswordStrengthLevel } from '/@/utils/toolsValidate';